---
- name: configure mongodb_uri cluster AUTO settings
  set_fact:
    graylog_mongodb_uri: "mongodb://{{ graylog_cluster_name }}:{{ mongo_graylog_password }}@{{ groups['mongo']|join(':27017,') }}:27017/{{ graylog_cluster_name }}?replicaSet={{ graylog_cluster_name }}"
  when: (( ansible_play_hosts_all|length ) > 1 ) and graylog_mongodb_uri == 'auto'

- name: configure mongodb_uri single-node AUTO settings
  set_fact:
    graylog_mongodb_uri: "mongodb://localhost/{{ uniqlog_cluster_name }}"
  when: (( ansible_play_hosts_all|length ) == 1 ) and graylog_mongodb_uri == 'auto'

...